# Generated by Django 2.2.1 on 2019-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('draft', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
